global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['host.docker.internal:9100']  # Via host since different networks

  - job_name: 'abctechnologies-app'
    static_configs:
      - targets: ['host.docker.internal:8082']  # Via host port mapping